angular.module('App').config(function($routeProvider,$locationProvider){
$routeProvider.when("/",
		{
		templateUrl:"/HelpYourselves/html/index.html",
		controller:"MainCtrl",
		controllerAs:"App"
		}
	)
	.when("/Menu",
			{
		templateUrl:"/HelpYourselves/partials/MenuItems.html",
		controller:"MainCtrl",
		controllerAs:"App"
	}
	)
	.when("/Location",
			{
		templateUrl:"/HelpYourselves/partials/Location.html",
		controller:"MainCtrl",
		controllerAs:"App"
	}
	)
	.when("/OrderOnline",{
		templateUrl:"/HelpYourselves/partials/OrderOnline.html",
		controller:"OrderOnlineCtrl",
		controllerAs:"App"
	}
	)
	.when("/Reviews",{
		templateUrl:"/HelpYourselves/partials/Reviews.html",
		controller:"MainCtrl",
		controllerAs:"App"
	}
	)
	.when("/ReviewOrder",{
		templateUrl:"/HelpYourselves/partials/ReviewOrder.html",
		controller:"OrderOnlineCtrl",
		controllerAs:"App"
	})
	.otherwise({
		  Template:"oops"
	  });
});